name: Plugin Auto-PR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dify CLI
        run: pip install dify-cli

      - name: Dify Plugin Marketplace Publish Action
        uses: langgenius/dify-marketplace-publish-action@main
        with:
          github_token: ${{ secrets.PLUGIN_ACTION }}
